app/auth_saml/__init__.py
from flask import Blueprint

bp = Blueprint('auth_saml', __name__)

from . import views

app/auth_saml/views.py
from flask import request, render_template, redirect, session, \
                  make_response, url_for, flash, current_app
from urllib.parse import urlparse
from flask_babel import _
from onelogin.saml2.auth import OneLogin_Saml2_Auth
from onelogin.saml2.utils import OneLogin_Saml2_Utils

# auth_saml stuff
from .tools import nocache
from . import bp as auth_saml_bp

# for current_app.logger
#import pprint

def init_saml_auth(req):
    if 'AUTH_SAML_SETTINGS_DICT' in current_app.config:
        auth = OneLogin_Saml2_Auth(req, custom_base_path=current_app.config['SAML_PATH'], old_settings=current_app.config['AUTH_SAML_SETTINGS_DICT'])
    else:
        auth = OneLogin_Saml2_Auth(req, custom_base_path=current_app.config['SAML_PATH'])
    return auth


def prepare_flask_request(request):
    # If server is behind proxys or balancers use the HTTP_X_FORWARDED fields
    url_data = urlparse(request.url)
    #Set lowercase_urlencoding=True if using ADFS as IdP, https://github.com/onelogin/python-saml/pull/144
    lowercase_urlencoding = current_app.config.get('AUTH_SAML_IDP_LC_URLENC', False)
    return {
        #'https': 'on' if request.scheme == 'https' else 'off',
        'https': 'on',
        'http_host': request.host,
        'server_port': url_data.port,
        'script_name': request.path,
        'get_data': request.args.copy(),
        'lowercase_urlencoding': lowercase_urlencoding,
        'post_data': request.form.copy()
    }

@auth_saml_bp.route('/', methods=['GET', 'POST'])
def index():
    req = prepare_flask_request(request)
    auth = init_saml_auth(req)
    errors = []
    error_reason = None
    not_auth_warn = False
    success_slo = False
    attributes = False
    paint_logout = False

    #hdrs = dict(request.headers)
    #current_app.logger.info('Info(/): Got header: '+pprint.pformat(hdrs))
    #current_app.logger.info('Info(/): Got req : '+pprint.pformat(req))
    #current_app.logger.info('Info(/): Got args: '+pprint.pformat(request.args))

    if 'samlUserdata' in session:
        paint_logout = True
        if len(session['samlUserdata']) > 0:
            attributes = session['samlUserdata'].items()

    #current_app.logger.info('Info(/)->out: render_template(index.html)')
    return render_template(
                'auth_saml/index.html',
                errors=errors,
                error_reason=error_reason,
                not_auth_warn=not_auth_warn,
                success_slo=success_slo,
                attributes=attributes,
                paint_logout=paint_logout
            )

def do_index_sso(url_for_arg):
    req = prepare_flask_request(request)
    auth = init_saml_auth(req)
    errors = []
    error_reason = None
    not_auth_warn = False
    success_slo = False
    attributes = False
    paint_logout = False

    #hdrs = dict(request.headers)
    #current_app.logger.info('Info(/sso): Got header: '+pprint.pformat(hdrs))
    #current_app.logger.info('Info(/sso): Got req : '+pprint.pformat(req))
    #current_app.logger.info('Info(/sso): Got args: '+pprint.pformat(request.args))

    return_to = url_for(url_for_arg)
    if 'url' in request.args:
        return_to = request.args['url']
        #current_app.logger.info('Info(/sso): Found arg url='+return_to)
    elif 'return_to' in request.args:
        return_to = request.args['return_to']
        #current_app.logger.info('Info(/sso): Found arg return_to='+return_to)
    #return redirect(return_to)
    # If AuthNRequest ID need to be stored in order to later validate it, do instead
    sso_built_url = auth.login(return_to)
    session['AuthNRequestID'] = auth.get_last_request_id()
    #current_app.logger.info('Info(/sso)->out: redirect(sso_built_url): ' + sso_built_url)
    return redirect(sso_built_url)

@auth_saml_bp.route('/sso', methods=['GET', 'POST'])
@nocache
def index_sso():
    return(do_index_sso('.index'))

@auth_saml_bp.route('/sso2', methods=['GET', 'POST'])
@nocache
def index_sso2():
    return(do_index_sso('.attrs'))

@auth_saml_bp.route('/slo', methods=['GET', 'POST'])
@nocache
def index_slo():
    req = prepare_flask_request(request)
    auth = init_saml_auth(req)
    errors = []
    error_reason = None
    not_auth_warn = False
    success_slo = False
    attributes = False
    paint_logout = False

    #hdrs = dict(request.headers)
    #current_app.logger.info('Info(/slo): Got header: '+pprint.pformat(hdrs))
    #current_app.logger.info('Info(/slo): Got req : '+pprint.pformat(req))
    #current_app.logger.info('Info(/slo): Got args: '+pprint.pformat(request.args))

    name_id = session_index = name_id_format = name_id_nq = name_id_spnq = None
    if 'samlNameId' in session:
        name_id = session['samlNameId']
    if 'samlSessionIndex' in session:
        session_index = session['samlSessionIndex']
    if 'samlNameIdFormat' in session:
        name_id_format = session['samlNameIdFormat']
    if 'samlNameIdNameQualifier' in session:
        name_id_nq = session['samlNameIdNameQualifier']
    if 'samlNameIdSPNameQualifier' in session:
        name_id_spnq = session['samlNameIdSPNameQualifier']

    return_to=None
    if 'url' in request.args:
        return_to = request.args['url']
        #current_app.logger.info('Info(/slo): Found arg url='+return_to)
    elif 'return_to' in request.args:
        return_to = request.args['return_to']
        #current_app.logger.info('Info(/slo): Found arg return_to='+return_to)

    #current_app.logger.info('Info(/slo)->out: redirect(auth.logout)')
    return redirect(auth.logout(return_to=return_to,
                       name_id=name_id,
                       session_index=session_index,
                       nq=name_id_nq,
                       name_id_format=name_id_format,
                       spnq=name_id_spnq))

@auth_saml_bp.route('/acs', methods=['GET', 'POST'])
@nocache
def index_acs():
    req = prepare_flask_request(request)
    auth = init_saml_auth(req)
    errors = []
    error_reason = None
    not_auth_warn = False
    success_slo = False
    attributes = False
    paint_logout = False

    #hdrs = dict(request.headers)
    #current_app.logger.info('Info(/acs): Got header: '+pprint.pformat(hdrs))
    #current_app.logger.info('Info(/acs): Got req : '+pprint.pformat(req))
    #current_app.logger.info('Info(/acs): Got args: '+pprint.pformat(request.args))

    request_id = None
    if 'AuthNRequestID' in session:
        request_id = session['AuthNRequestID']

    auth.process_response(request_id=request_id)
    errors = auth.get_errors()
    not_auth_warn = not auth.is_authenticated()
    if len(errors) == 0:
        if 'AuthNRequestID' in session:
            del session['AuthNRequestID']
        session['samlUserdata'] = auth.get_attributes()
        session['samlNameId'] = auth.get_nameid()
        session['samlNameIdFormat'] = auth.get_nameid_format()
        session['samlNameIdNameQualifier'] = auth.get_nameid_nq()
        session['samlNameIdSPNameQualifier'] = auth.get_nameid_spnq()
        session['samlSessionIndex'] = auth.get_session_index()
        self_url = OneLogin_Saml2_Utils.get_self_url(req)
        if 'RelayState' in request.form and self_url != request.form['RelayState']:
            #current_app.logger.info('Info(/acs)->out: Got RelayState: '+pprint.pformat(request.form['RelayState']))
            return redirect(auth.redirect_to(request.form['RelayState']))
    elif auth.get_settings().is_debug_active():
        error_reason = auth.get_last_error_reason()

    if 'samlUserdata' in session:
        paint_logout = True
        if len(session['samlUserdata']) > 0:
            attributes = session['samlUserdata'].items()

    #current_app.logger.info('Info(/acs)->out: render_template(auth_saml/index.html)')
    return render_template(
                'auth_saml/index.html',
                errors=errors,
                error_reason=error_reason,
                not_auth_warn=not_auth_warn,
                success_slo=success_slo,
                attributes=attributes,
                paint_logout=paint_logout
            )

@auth_saml_bp.route('/sls', methods=['GET', 'POST'])
@nocache
def index_sls():
    req = prepare_flask_request(request)
    auth = init_saml_auth(req)
    errors = []
    error_reason = None
    not_auth_warn = False
    success_slo = False
    attributes = False
    paint_logout = False

    #hdrs = dict(request.headers)
    #current_app.logger.info('Info(/sls): Got header: '+pprint.pformat(hdrs))
    #current_app.logger.info('Info(/sls): Got req : '+pprint.pformat(req))
    #current_app.logger.info('Info(/sls): Got args: '+pprint.pformat(request.args))

    request_id = None
    if 'LogoutRequestID' in session:
        request_id = session['LogoutRequestID']
    dscb = lambda: session.clear()
    url = auth.process_slo(request_id=request_id, delete_session_cb=dscb)
    # BUG(?): There seems to be a problem with auth.process_slo(). It does not
    # give back the url in RelayState.
    errors = auth.get_errors()
    #current_app.logger.info('Info(/sls) url='+str(url)+' errors='+str(len(errors)))
    if len(errors) == 0:
        if url is None:
            # begin: try to go around the BUG
            get_data = 'get_data' in req and req['get_data']
            if get_data and 'RelayState' in get_data:
                url1 = get_data['RelayState']
                url2 = current_app.config.get('AUTH_SAML_SP_SLO_URL', "")
                url1_low = url1.lower()
                if url2 is not None:
                    url2_low = url2.lower()
                else:
                    url2_low = ""
                if url1_low != url2_low:
                    url = url1
                elif url2_low != "":
                    url = url2
            # end: try to go around the BUG
        if url is not None:
            #current_app.logger.info('Info(/sls)->out: sls out via redirect url: ' + url)
            return redirect(url)
        else:
            flash('User successfully logged out.', 'info')

app/templates/auth_saml/attrs.html
{% extends "auth_saml/base.html" %}

{% block content %}

<h1>{% if title %}{{ title }}{% else %}An Authentication Service powered by Python SAML Toolkit.{% endif %}</h1>

{% if paint_logout %}
  {% if attributes %}
    <p>{{ _("You have the following attributes:") }}</p>
    <table class="table table-striped">
      <thead>
        <th>{{ _("Name") }}</th><th>{{ _("Values") }}</th>
      </thead>
      <tbody>
        {% for attr in attributes %}
          <tr><td>{{ attr.0 }}</td>
          <td><ul class="list-unstyled">
            {% for val in attr.1 %}
              <li>{{ val }}</li>
            {% endfor %}
          </ul></td></tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <div class="alert alert-danger" role="alert">{{ _("You don't have any attributes.") }}</div>
  {% endif %}
  <a href="{{ url_for('auth_saml.index_slo') }}" class="btn btn-danger">{{ _("Logout") }}</a>
{% else %}
<a href="{{ url_for('auth_saml.index_sso2') }}" class="btn btn-primary">{{ _("Login and access again to this page") }}</a>
{% endif %}

{% endblock %}

app/templates/auth_saml/auth_check.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Cache-Control" content="no-cache,no-store,must-revalidate"/>
<meta http-equiv="Pragma" content="no-cache"/>
<meta http-equiv="Expires" content="0"/>
<meta charset="utf-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
<title>{% if title %}{{ title }}{% else %}An Auth APP with use of Python SAML Toolkit provided by OneLogin.{% endif %}</title>
</head>
<body>
<h1>{% if title %}{{ title }}{% else %}An Authentication Service powered by Python SAML Toolkit.{% endif %}</h1>
{% if paint_logout %}
{% if attributes %}
<p>{{ _("You have the following attributes:") }}</p>
<table>
<thead>
<th>{{ _("Name") }}</th><th>{{ _("Values") }}</th>
</thead>
<tbody>
{% for attr in attributes %}
{% for val in attr.1 %}
<tr>
  <td>{{ attr.0 }}</td>
  <td>{{ val }}</td>
</tr>
{% endfor %}
{% endfor %}
</tbody>
</table>
{% else %}
<p>{{ _("You don't have any attributes.") }}</p>
{% endif %}
<a href="{{ url_for('auth_saml.index_slo') }}?url={{ url_for('auth_saml.auth_check') }}">{{ _("Logout") }}</a>
{% else %}
<a href="{{ url_for('auth_saml.index_sso') }}?url={{ url_for('auth_saml.auth_check') }}">{{ _("Login and access again to this page") }}</a>
{% endif %}
</body>
</html>

app/templates/auth_saml/base.html
{% extends 'bootstrap/base.html' %}
  
{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="icon"          href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
{% endblock %}

{% block title %}
    {% if title %}{{ title }}{% else %}An Auth APP with use of Python SAML Toolkit provided by OneLogin.{% endif %}
{% endblock %}


{% block content %}
{% endblock %}

app/templates/auth_saml/index.html
{% extends "auth_saml/base.html" %}

{% block content %}

<h1>{% if title %}{{ title }}{% else %}An Authentication Service powered by Python SAML Toolkit.{% endif %}</h1>

{% if errors %}
  <div class="alert alert-danger" role="alert">
    <strong>{{ _("Errors:") }}</strong>
    <ul class="list-unstyled">
        {% for err in errors %}
          <li>{{err}}</li>
        {% endfor %}
    </ul>
    {% if error_reason %}
        <span>{{error_reason}}</span>
    {% endif %}
  </div>
{% endif %}

{% if not_auth_warn %}
  <div class="alert alert-danger" role="alert">{{ _("Not authenticated") }}</div>
{% endif %}

{% if success_slo %}
  <div class="alert alert-success" role="alert">{{ _("Successfully logged out") }}</div>
{% endif %}

{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
    {% for category, message in messages %}
    <div class="alert alert-{{ category }}" role="alert">{{ message }}</div>
    {% endfor %}
{% endif %}
{% endwith %}

{% if paint_logout %}
  {% if attributes %}
    <table class="table table-striped">
      <thead>
        <th>{{ _("Name") }}</th><th>{{ _("Values") }}</th>
      </thead>
      <tbody>
        {% for attr in attributes %}
          <tr><td>{{ attr.0 }}</td>
          <td><ul class="list-unstyled">
            {% for val in attr.1 %}
              <li>{{ val }}</li>
            {% endfor %}
          </ul></td></tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <div class="alert alert-danger" role="alert">{{ _("You don't have any attributes.") }}</div>
  {% endif %}
  <a href="{{ url_for('auth_saml.index_slo') }}" class="btn btn-danger">{{ _("Logout") }}</a>
{% else %}
  <a href="{{ url_for('auth_saml.index_sso') }}" class="btn btn-primary">{{ _("Login") }}</a>
  <a href="{{ url_for('auth_saml.index_sso2') }}" class="btn btn-info">{{ _("Login and access again to this page") }}</a>
{% endif %}

{% endblock %}